import { expect, test } from "@playwright/test";
import os from "node:os";
import path from "node:path";
import { expectNoOverflow, loginAdmin } from "./support/accessibility";
import { createArticle } from "./support/articles";
import { E2E_API_URL, E2E_APP_URL } from "./support/test-env";

for (const theme of ["dark", "light"]) test(`post actions open from the More control in ${theme}`, async ({ page, context }) => {
  await context.addCookies([{ name: "blog_theme", value: theme, url: E2E_APP_URL }]);
  const headers = await loginAdmin(page);
  const suffix = `${theme}-${Date.now()}`;
  const postTitle = `Delete hint ${suffix}`;
  const otherPostTitle = `Other hint ${suffix}`;
  const response = await createArticle(page.request, { headers, data: { title: postTitle, content: "Tooltip test", status: "draft", category_id: 0 } });
  const post = await response.json();
  const otherResponse = await createArticle(page.request, { headers, data: { title: otherPostTitle, content: "Other post", status: "draft", category_id: 0 } });
  const otherPost = await otherResponse.json();
  try {
    await page.goto("/editor");
    const row = page.locator(".editor-post-card").filter({ hasText: post.title });
    const otherRow = page.locator(".editor-post-card").filter({ hasText: otherPost.title });
    const otherTitle = otherRow.getByText(otherPost.title, { exact: true });
    const more = row.getByRole("button", { name: `More actions for ${postTitle}` });
    const normalRowBackground = await row.evaluate(node => getComputedStyle(node).backgroundColor);
    const normalOtherBackground = await otherRow.evaluate(node => getComputedStyle(node).backgroundColor);
    const rowIndicatorOpacity = () => row.evaluate(node => getComputedStyle(node, "::after").opacity);
    const rowWashOpacity = () => row.evaluate(node => getComputedStyle(node, "::before").opacity);
    const otherIndicatorOpacity = () => otherRow.evaluate(node => getComputedStyle(node, "::after").opacity);
    const normalOtherTitleColor = await otherTitle.evaluate(node => getComputedStyle(node).color);
    const normalMoreBackground = await more.evaluate(node => getComputedStyle(node).backgroundColor);
    expect(await rowIndicatorOpacity()).toBe("0");
    expect(await rowWashOpacity()).toBe("0");
    await more.hover();
    await expect.poll(() => row.evaluate(node => getComputedStyle(node).backgroundColor)).toBe(normalRowBackground);
    await expect.poll(rowIndicatorOpacity).toBe("1");
    await expect.poll(rowWashOpacity).toBe("1");
    expect(await row.evaluate(node => getComputedStyle(node, "::after").width)).toBe("2px");
    expect(await row.evaluate(node => getComputedStyle(node, "::after").transitionProperty)).toBe("opacity");
    await expect.poll(() => more.evaluate(node => getComputedStyle(node).backgroundColor)).not.toBe(normalMoreBackground);
    const moreBox = await more.boundingBox();
    expect(moreBox!.width).toBeLessThan(70);
    expect(moreBox!.height).toBe(30);
    await expect(row.getByRole("button", { name: "Delete", exact: true })).toHaveCount(0);
    await expect(page.getByRole("alertdialog")).toHaveCount(0);
    await page.screenshot({ path: path.join(os.tmpdir(), `blog-post-delete-hint-${theme}.png`) });
    await more.focus();
    await more.press("Enter");
    const desktopMenu = row.getByRole("group", { name: `Actions for ${postTitle}` });
    await expect(desktopMenu).toBeVisible();
    await expect(desktopMenu).toHaveCSS("opacity", "1");
    expect(await desktopMenu.evaluate(node => getComputedStyle(node).transitionDuration)).toContain("0.16s");
    await expect(row.getByRole("button", { name: "Delete", exact: true })).toBeVisible();
    await page.getByRole("heading", { name: "Content Editor" }).hover();
    await expect(more).toHaveAttribute("aria-expanded", "true");
    await expect.poll(() => row.evaluate(node => getComputedStyle(node).backgroundColor)).toBe(normalRowBackground);
    await expect.poll(rowIndicatorOpacity).toBe("1");
    await expect.poll(() => more.evaluate(node => getComputedStyle(node).backgroundColor)).toBe(normalMoreBackground);
    await otherRow.getByRole("button", { name: `Open ${otherPostTitle}` }).hover();
    await expect.poll(() => otherRow.evaluate(node => getComputedStyle(node).backgroundColor)).toBe(normalOtherBackground);
    await expect.poll(otherIndicatorOpacity).toBe("1");
    await expect(otherTitle).not.toHaveCSS("color", normalOtherTitleColor);
    await expect.poll(rowIndicatorOpacity).toBe("1");
    await expect(more).toHaveAttribute("aria-expanded", "true");
    await desktopMenu.hover();
    await expect.poll(rowIndicatorOpacity).toBe("1");
    await page.keyboard.press("Escape");
    await expect(more).toBeFocused();
    await expect(row.getByRole("button", { name: "Delete", exact: true })).toHaveCount(0);
    await expect(row.locator('[role="group"]')).toHaveCSS("visibility", "hidden");
    await otherRow.getByRole("button", { name: `Open ${otherPostTitle}` }).hover();
    await expect.poll(otherIndicatorOpacity).toBe("1");
    await page.setViewportSize({ width: 375, height: 850 });
    await more.scrollIntoViewIfNeeded();
    await more.click();
    const menu = row.getByRole("group", { name: `Actions for ${postTitle}` });
    await expect(menu).toBeVisible();
    await expect(menu).toHaveCSS("opacity", "1");
    const menuBox = await menu.boundingBox();
    const rowBox = await row.boundingBox();
    expect(menuBox!.x).toBeGreaterThanOrEqual(0);
    expect(menuBox!.x + menuBox!.width).toBeLessThanOrEqual(375);
    expect(menuBox!.y >= rowBox!.y + rowBox!.height - 2 || menuBox!.y + menuBox!.height <= rowBox!.y + 2).toBe(true);
    await expectNoOverflow(page);
    await page.screenshot({ path: path.join(os.tmpdir(), `blog-post-actions-mobile-${theme}.png`) });
    await page.keyboard.press("Escape");
    await row.getByRole("button", { name: `Open ${postTitle}` }).click();
    await expect(page).toHaveURL(url => url.pathname === "/editor" && url.searchParams.get("edit") === String(post.id));
  } finally {
    await page.request.delete(`${E2E_API_URL}/admin/posts/${post.id}`, { headers });
    await page.request.delete(`${E2E_API_URL}/admin/posts/${otherPost.id}`, { headers });
  }
});
